--------------------------------------------------------
--  File created - Monday-May-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINISTRATOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADMINISTRATOR" 
   (	"ADMIN_HASHEDID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMIN_USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMIN_FNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMIN_LNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ADMIN_DOB" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ADMINISTRATOR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADMIN_PK" ON "SYSTEM"."ADMINISTRATOR" ("ADMIN_HASHEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMINISTRATOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADMINISTRATOR" MODIFY ("ADMIN_HASHEDID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMINISTRATOR" MODIFY ("ADMIN_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMINISTRATOR" MODIFY ("ADMIN_FNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMINISTRATOR" MODIFY ("ADMIN_LNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMINISTRATOR" MODIFY ("ADMIN_DOB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADMINISTRATOR" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_HASHEDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
