--------------------------------------------------------
--  File created - Wednesday-April-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLICANT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."APPLICANT" 
   (	"A_HASHEDID" NUMBER, 
	"A_USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"A_FNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"A_LNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"A_DOB" DATE, 
	"A_RESUMEPDF" BLOB, 
	"A_TECH_YEARSOFEXP" NUMBER, 
	"A_TECH_PROBLEMSOLVING" NUMBER, 
	"A_TECH_DEGREE" NUMBER, 
	"A_BUSI_JOBTYPE" NUMBER, 
	"A_BUSI_GROWTHOPP" NUMBER, 
	"A_BUSI_COMPANYSIZE" NUMBER, 
	"A_CULT_CONSISTENCY" NUMBER, 
	"A_CULT_COMMUNICATION" NUMBER, 
	"A_CULT_LEADERSHIP" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("A_RESUMEPDF") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.APPLICANT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APPLICANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."APPLICANT_PK" ON "SYSTEM"."APPLICANT" ("A_HASHEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table APPLICANT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_HASHEDID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_DOB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_RESUMEPDF" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_TECH_YEARSOFEXP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_TECH_PROBLEMSOLVING" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_TECH_DEGREE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_BUSI_JOBTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_BUSI_GROWTHOPP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_BUSI_COMPANYSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_CULT_CONSISTENCY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_CULT_COMMUNICATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" MODIFY ("A_CULT_LEADERSHIP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."APPLICANT" ADD CONSTRAINT "APPLICANT_PK" PRIMARY KEY ("A_HASHEDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
