--------------------------------------------------------
--  File created - Monday-May-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYER" 
   (	"E_HASHEDID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"E_COMPANYNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"E_USERNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"E_FNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"E_LNAME" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"E_DOB" DATE, 
	"E_JOBLISTINGPDF" BLOB, 
	"E_TECH_YEARSOFEXP" NUMBER, 
	"E_TECH_PROBLEMSOLVING" NUMBER, 
	"E_TECH_DEGREE" NUMBER, 
	"E_BUSI_JOBTYPE" NUMBER, 
	"E_BUSI_GROWTHOPP" NUMBER, 
	"E_BUSI_COMPANYSIZE" NUMBER, 
	"E_CULT_CONSISTENCY" NUMBER, 
	"E_CULT_COMMUNICATION" NUMBER, 
	"E_CULT_LEADERSHIP" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("E_JOBLISTINGPDF") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.EMPLOYER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYER_PK" ON "SYSTEM"."EMPLOYER" ("E_HASHEDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_HASHEDID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_COMPANYNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_FNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_LNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_DOB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_TECH_YEARSOFEXP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_TECH_PROBLEMSOLVING" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_TECH_DEGREE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_BUSI_JOBTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_BUSI_GROWTHOPP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_BUSI_COMPANYSIZE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_CULT_CONSISTENCY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_CULT_COMMUNICATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" MODIFY ("E_CULT_LEADERSHIP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYER" ADD CONSTRAINT "EMPLOYER_PK" PRIMARY KEY ("E_HASHEDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;